version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: always
    container_name: "minecraft"
    environment:
      MEMORYSIZE: "8G"
      PAPERMC_FLAGS: ""
      TZ: "Etc/UTC"
    volumes:
      - "/opt/minecraft-rt/data:/data:rw"
    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "19132:19132/udp"
      - "19133:19133/udp"
    stdin_open: true
    tty: true